#!/bin/sh

APP=supertuxkart

mkdir tmp;
cd ./tmp;
wget -q $(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | grep -v zsync | grep -i continuous | grep -i appimagetool | grep -i x86_64 | grep browser_download_url | cut -d '"' -f 4 | head -1) -O appimagetool
mv ./appimagetool-x86_64.AppImage ./appimagetool
chmod a+x ./appimagetool

for arch in "64bit" "x86_64"
do
wget https:$(curl -s https://api.github.com/repos/supertuxkart/stk-code/releases/latest | grep browser_download_url | egrep '/.*/.*/.*linux-'$arch'.tar.xz' -o)
tar xf ./*.tar.xz;
mv ./SuperTuxKart-*-linux-$arch ./$APP.AppDir
done

echo "[Desktop Entry]
Name=SuperTuxKart
Icon=supertuxkart
GenericName=A kart racing game
GenericName[da]=Et kart racerspil
GenericName[de]=Ein Kart-Rennspiel
GenericName[fr]=Un jeu de karting
GenericName[gl]=Xogo de carreiras con karts
GenericName[pl]=Wyścigi gokartów
GenericName[ro]=Un joc de curse cu carturi
Exec=supertuxkart
Terminal=false
StartupNotify=false
Type=Application
Categories=Game;ArcadeGame;
Keywords=tux;game;race;" >> ./$APP.AppDir/$APP.desktop;
cp ./$APP.AppDir/data/supertuxkart_512.png ./$APP.AppDir;
mv ./$APP.AppDir/supertuxkart_512.png ./$APP.AppDir/$APP.png
mv ./$APP.AppDir/run_game.sh ./$APP.AppDir/AppRun;

ARCH=x86_64 VERSION=$(./appimagetool -v | grep -o '[[:digit:]]*') ./appimagetool -s ./$APP.AppDir;

cd ..;
mv ./tmp/*mage ./$APP.AppImage;


echo "";
echo "   SuperTuxKart is provided by https://supertuxkart.net";
echo "";
echo " This AppImage is created using the official build for Linux";
echo "";
