#!/bin/sh

APP=supertuxkart

mkdir tmp;
cd ./tmp;


wget https://github.com/$(wget https://github.com/supertuxkart/stk-code/releases/latest -O - | egrep '/.*/.*/.*linux-64bit.tar.xz' -o);

tar xf ./*.tar.xz;
mv ./SuperTuxKart-*-linux-64bit ./$APP.AppDir;
echo "[Desktop Entry]
Name=SuperTuxKart
Icon=supertuxkart
GenericName=A kart racing game
GenericName[da]=Et kart racerspil
GenericName[de]=Ein Kart-Rennspiel
GenericName[fr]=Un jeu de karting
GenericName[gl]=Xogo de carreiras con karts
GenericName[pl]=Wyścigi gokartów
GenericName[ro]=Un joc de curse cu carturi
Exec=supertuxkart
Terminal=false
StartupNotify=false
Type=Application
Categories=Game;ArcadeGame;
Keywords=tux;game;race;" >> ./$APP.AppDir/$APP.desktop;
cp ./$APP.AppDir/data/supertuxkart_512.png ./$APP.AppDir;
mv ./$APP.AppDir/supertuxkart_512.png ./$APP.AppDir/$APP.png
mv ./$APP.AppDir/run_game.sh ./$APP.AppDir/AppRun;

ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;
mv ./tmp/*mage ./$APP;


echo "";
echo "   SuperTuxKart is provided by https://supertuxkart.net";
echo "";
echo " This AppImage is created using the official build for Linux";
echo "";
